# iwgtk
# Autogenerated from man page /usr/share/man/man1/iwgtk.1.gz
complete -c iwgtk -s n -l notifications -d 'Enable desktop notifications (default)'
complete -c iwgtk -s N -l no-notifications -d 'Disable desktop notifications'
complete -c iwgtk -s h -l help -d 'Show command line options and quit'
complete -c iwgtk -s V -l version -d 'Print version number and quit'

